// import 'package:piano/piano.dart';

import 'package:whistle/ScorePainter/NotePosition.dart';

var notes = {
  'rest': [],
  //0th octave
  'C0': [Note.C, Accidental.None, 0],
  'C#0': [Note.C, Accidental.Sharp, 0],
  'D0': [Note.D, Accidental.None, 0],
  'D#0': [Note.D, Accidental.Sharp, 0],
  'E0': [Note.E, Accidental.None, 0],
  'F0': [Note.F, Accidental.None, 0],
  'F#0': [Note.F, Accidental.Sharp, 0],
  'G0': [Note.G, Accidental.None, 0],
  'G#0': [Note.G, Accidental.Sharp, 0],
  'A0': [Note.A, Accidental.None, 0],
  'A#0': [Note.A, Accidental.Sharp, 0],
  'B0': [Note.B, Accidental.None, 0],

  //1st Octave
  'C1': [Note.C, Accidental.None, 1],
  'C#1': [Note.C, Accidental.Sharp, 1],
  'D1': [Note.D, Accidental.None, 1],
  'D#1': [Note.D, Accidental.Sharp, 1],
  'E1': [Note.E, Accidental.None, 1],
  'F1': [Note.F, Accidental.None, 1],
  'F#1': [Note.F, Accidental.Sharp, 1],
  'G1': [Note.G, Accidental.None, 1],
  'G#1': [Note.G, Accidental.Sharp, 1],
  'A1': [Note.A, Accidental.None, 1],
  'A#1': [Note.E, Accidental.None, 1],
  'B1': [Note.E, Accidental.None, 1],

  //2nd Octave
  'C2': [Note.C, Accidental.None, 2],
  'C#2': [Note.C, Accidental.Sharp, 2],
  'D2': [Note.D, Accidental.None, 2],
  'D#2': [Note.D, Accidental.Sharp, 2],
  'E2': [Note.E, Accidental.None, 2],
  'F2': [Note.F, Accidental.None, 2],
  'F#2': [Note.F, Accidental.Sharp, 2],
  'G2': [Note.G, Accidental.None, 2],
  'G#2': [Note.G, Accidental.Sharp, 2],
  'A2': [Note.A, Accidental.None, 2],
  'A#2': [Note.E, Accidental.None, 2],
  'B2': [Note.E, Accidental.None, 2],

  //3rd Octave
  'C3': [Note.C, Accidental.None, 3],
  'C#3': [Note.C, Accidental.Sharp, 3],
  'D3': [Note.D, Accidental.None, 3],
  'D#3': [Note.D, Accidental.Sharp, 3],
  'E3': [Note.E, Accidental.None, 3],
  'F3': [Note.F, Accidental.None, 3],
  'F#3': [Note.F, Accidental.Sharp, 3],
  'G3': [Note.G, Accidental.None, 3],
  'G#3': [Note.G, Accidental.Sharp, 3],
  'A3': [Note.A, Accidental.None, 3],
  'A#3': [Note.E, Accidental.None, 3],
  'B3': [Note.E, Accidental.None, 3],

  //4th Octave
  'C4': [Note.C, Accidental.None, 4],
  'C#4': [Note.C, Accidental.Sharp, 4],
  'D4': [Note.D, Accidental.None, 4],
  'D#4': [Note.D, Accidental.Sharp, 4],
  'E4': [Note.E, Accidental.None, 4],
  'F4': [Note.F, Accidental.None, 4],
  'F#4': [Note.F, Accidental.Sharp, 4],
  'G4': [Note.G, Accidental.None, 4],
  'G#4': [Note.G, Accidental.Sharp, 4],
  'A4': [Note.A, Accidental.None, 4],
  'A#4': [Note.E, Accidental.None, 4],
  'B4': [Note.E, Accidental.None, 4],

  //5th Octave
  'C5': [Note.C, Accidental.None, 5],
  'C#5': [Note.C, Accidental.Sharp, 5],
  'D5': [Note.D, Accidental.None, 5],
  'D#5': [Note.D, Accidental.Sharp, 5],
  'E5': [Note.E, Accidental.None, 5],
  'F5': [Note.F, Accidental.None, 5],
  'F#5': [Note.F, Accidental.Sharp, 5],
  'G5': [Note.G, Accidental.None, 5],
  'G#5': [Note.G, Accidental.Sharp, 5],
  'A5': [Note.A, Accidental.None, 5],
  'A#5': [Note.E, Accidental.None, 5],
  'B5': [Note.E, Accidental.None, 5],

  //6th Octave
  'C6': [Note.C, Accidental.None, 6],
  'C#6': [Note.C, Accidental.Sharp, 6],
  'D6': [Note.D, Accidental.None, 6],
  'D#6': [Note.D, Accidental.Sharp, 6],
  'E6': [Note.E, Accidental.None, 6],
  'F6': [Note.F, Accidental.None, 6],
  'F#6': [Note.F, Accidental.Sharp, 6],
  'G6': [Note.G, Accidental.None, 6],
  'G#6': [Note.G, Accidental.Sharp, 6],
  'A6': [Note.A, Accidental.None, 6],
  'A#6': [Note.E, Accidental.None, 6],
  'B6': [Note.E, Accidental.None, 6],

  //7th Octave
  'C7': [Note.C, Accidental.None, 7],
  'C#7': [Note.C, Accidental.Sharp, 7],
  'D7': [Note.D, Accidental.None, 7],
  'D#7': [Note.D, Accidental.Sharp, 7],
  'E7': [Note.E, Accidental.None, 7],
  'F7': [Note.F, Accidental.None, 7],
  'F#7': [Note.F, Accidental.Sharp, 7],
  'G7': [Note.G, Accidental.None, 7],
  'G#7': [Note.G, Accidental.Sharp, 7],
  'A7': [Note.A, Accidental.None, 7],
  'A#7': [Note.E, Accidental.None, 7],
  'B7': [Note.E, Accidental.None, 7],

  //8th Octave
  'C8': [Note.C, Accidental.None, 8],
  'C#8': [Note.C, Accidental.Sharp, 8],
  'D8': [Note.D, Accidental.None, 8],
  'D#8': [Note.D, Accidental.Sharp, 8],
  'E8': [Note.E, Accidental.None, 8],
  'F8': [Note.F, Accidental.None, 8],
  'F#8': [Note.F, Accidental.Sharp, 8],
  'G8': [Note.G, Accidental.None, 8],
  'G#8': [Note.G, Accidental.Sharp, 8],
  'A8': [Note.A, Accidental.None, 8],
  'A#8': [Note.E, Accidental.None, 8],
  'B8': [Note.E, Accidental.None, 8],
};
