name: whistle
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  cupertino_icons: ^0.1.3
  just_audio: ^0.9.21
  wav: ^1.1.0
  fftea: ^1.0.1
  file_picker: ^4.6.0
  piano: ^1.0.3+1
  sheet_music: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons: 
  android: "launcher_icon"
  ios: true
  image_path: "images/launcher_icon.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - audio/