name: whistle
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  cupertino_icons: ^0.1.3
  just_audio: ^0.9.21
  wav: ^1.1.0
  fftea: ^1.0.1
  file_picker: ^4.6.0
  piano: ^1.0.3+1
  sheet_music: ^0.3.0
  ffmpeg_kit_flutter: ^4.5.1
  path_provider: ^2.0.10
  flutter_sound: ^9.2.13
  permission_handler: ^10.0.0
  flutter_spinkit: ^5.1.0
  wave_progress_bars: ^0.1.0
  flutter_svg: ^0.17.4
  curved_navigation_bar: ^1.0.3
  freezed_annotation: ^0.14.3
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+4
  quiver: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons: 
  android: "launcher_icon"
  ios: true
  image_path: "images/launcher_icon.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - audio/
    - images/LoadingScreen/